name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clone: 
    name: Clone
    runs-on: ubuntu-latest
    steps:
    - name: Setup SSH
      uses: kevin-leptons/ssh_action@v1
      with:
        host: ubuntu@3.85.165.37
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        command: mkdir -p praveen
